sicovg/core/principales/urls.py
from django.urls import path
from core.principales.principalesviews.views import DashboardView


app_name = 'principales'

urlpatterns = [
    path('dashboard/', DashboardView.as_view(), name='dashboard'),

]

sicovg/sicovg/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from sicovg import settings
urlpatterns = [
    path('', include('core.login.urls')),
    path('Inicio/', include('core.principales.urls')),
    path('Clientes/', include('core.Clientes.urls')),
    path('Proovedores/', include('core.Proovedores.urls')),
    path('Inventario/', include('core.Inventario.urls')),
    path('Ventas/', include('core.Ventas.urls')),
    path('rh/', include('core.rh.urls')),
    path('Agendacalend/', include('core.Agendacalend.urls')),
]

sicovg/core/principales/models.py
from django.db import models
from django.forms import model_to_dict
from datetime import datetime
from datetime import date
from core.login.models import User


class Clientes(models.Model):
    idCliente = models.AutoField(primary_key=True, verbose_name='idCliente')
    razonSocial = models.CharField(max_length=256, verbose_name='Razon social', null=False, unique=False)
    cuenta = models.CharField(max_length=6, verbose_name='Numero de cuenta', null=False, unique=False)
    email = models.CharField(max_length=128, verbose_name='Email', blank=True, null=True)
    RFC = models.CharField(max_length=18, verbose_name='RFC', unique=False)
    calle = models.CharField(max_length=128, verbose_name='Calle', null=True, blank=True)
    noExt = models.CharField(max_length=15, verbose_name='No exterior', default='SN', blank=True)
    noInt = models.CharField(max_length=15, verbose_name='No Interior', default='SN', blank=True)
    codigoPostal = models.CharField(verbose_name='Codigo Postal', max_length=5, null=True, blank=True)
    municipio = models.CharField(verbose_name='Municipio', max_length=128, null=True, blank=True)
    estado = models.CharField(verbose_name='Estado', max_length=64, null=True, blank=True)
    colonia = models.CharField(verbose_name='Colonia', max_length=128, null=True, blank=True)
    telefono = models.CharField(max_length=10, verbose_name='Telefono', null=True, blank=True)

    class Meta:
        db_table = 'Cliente'
        verbose_name = 'cliente'
        verbose_name_plural = 'Clientes'

    def toJSON(self):
        item = model_to_dict(self)
        return item


class Proovedor(models.Model):
    idProveedor = models.AutoField(primary_key=True, verbose_name='idProveedor')
    razonSocial = models.CharField(max_length=256, null=False, unique=False)
    cuenta = models.CharField(max_length=10, verbose_name='Cuenta', unique=True)
    RFC = models.CharField(max_length=18, verbose_name='RFC', unique=False)
    codigoPostal = models.CharField(verbose_name='Codigo Postal', max_length=5, null=True, blank=True)
    municipio = models.CharField(verbose_name='Municipio', max_length=128, null=True, blank=True)
    estado = models.CharField(verbose_name='Estado', max_length=64, null=True, blank=True)
    colonia = models.CharField(verbose_name='Colonia', max_length=128, null=True, blank=True)
    telefono = models.CharField(max_length=10, verbose_name='Telefono', null=True, blank=True)
    email = models.CharField(max_length=128, verbose_name='Email', blank=True, null=True)
    activo = models.CharField(max_length=5, verbose_name='Activo', null=True, blank=True)
    representanteLegal = models.CharField(max_length=128, verbose_name='Representante legal', null=True, blank=True)

    class Meta:
        db_table = 'Proovedor'
        verbose_name = 'Proovedor'
        verbose_name_plural = 'Proovedores'

    def toJSON(self):
        item = model_to_dict(self)
        return item


class Inventario(models.Model):
    idInventario = models.AutoField(primary_key=True, verbose_name='idInventario')
    NombresProducto = models.CharField(max_length=100, verbose_name='Nombre Producto', null=False)
    Descripcion = models.CharField(max_length=200, verbose_name=' Descripcion', null=False)
    Categoria = models.CharField(max_length=100, verbose_name='Categoria ', null=False)
    NumeroDeSerie = models.CharField(max_length=20, verbose_name=' Numero De Serie', null=False)
    CantidadDeStock = models.IntegerField(verbose_name=' Cantidad En Stock', null=False)
    PrecioUnitario = models.FloatField(max_length=50, verbose_name=' Precio Unitario', null=False)
    PrecioDeCompra = models.FloatField(max_length=50, verbose_name=' Precio De Compra', null=False)
    FechaDeCompra = models.DateField(default=datetime.now, verbose_name='Fecha De Compra', null=False)
    NivelDeReordenamiento = models.IntegerField(verbose_name=' Numero De Ordenamiento ', null=False)

    class Meta:
        db_table = 'Inventario'
        verbose_name = 'Inventario'
        verbose_name_plural = 'Inventarios'

    def toJSON(self):
        item = model_to_dict(self)
        return item


class Venta(models.Model):
    idVenta = models.AutoField(primary_key=True, verbose_name='idVenta')
    clienteId = models.ForeignKey(Clientes, verbose_name='idCliente', on_delete=models.PROTECT)
    colaboradorId = models.ForeignKey(User, verbose_name=id, on_delete=models.PROTECT)
    totalDeVentas = models.FloatField(max_length=50, verbose_name='Total de Venta', null=False)
    fechaDeCompra = models.DateField(default=date.today, verbose_name='Fecha de Compra', null=False)
    estatus = models.CharField(max_length=100, verbose_name='Estatus', null=False)
    comentario = models.CharField(max_length=250, verbose_name='Estatus', null=False)

    class Meta:
        db_table = 'Venta'
        verbose_name = 'Venta'
        verbose_name_plural = 'Ventas'

    def toJSON(self):
        item = model_to_dict(self)
        return item


class DetalleVenta(models.Model):
    idDetalleVenta = models.AutoField(primary_key=True, verbose_name='idDetalleVenta')
    ventaId = models.ForeignKey(Venta, verbose_name='idVenta', on_delete=models.PROTECT)
    inventarioId = models.ForeignKey(Inventario, verbose_name='idInventario', on_delete=models.PROTECT)
    cantidad = models.IntegerField(verbose_name='Cantidad', null=False)
    precioUnitario = models.FloatField(max_length=50, verbose_name='Precio Unitario', null=False)
    precioTotal = models.FloatField(max_length=50, verbose_name='Precio Total', null=False)
    fechaDeCompra = models.DateField(default=date.today, verbose_name='Fecha de Compra', null=False)

    class Meta:
        db_table = 'DetalleVenta'
        verbose_name = 'DetalleVenta'
        verbose_name_plural = 'DetalleVentas'

    def toJSON(self):
        item = model_to_dict(self)
        return item


class Asistencia(models.Model):
    idAsistencia = models.AutoField(primary_key=True, verbose_name="idAsistencia")
    colaborador = models.ForeignKey(User, verbose_name='idColaborador', on_delete=models.PROTECT,
                                    related_name='idColaborador')
    fechaAsistencia = models.DateField(default=datetime.now, verbose_name="Fecha Asistencia", null=True, blank=True)
    estatus = models.CharField(max_length=100, verbose_name='estatus', null=True, blank=True)

    class Meta:
        db_table = 'Asistencia'
        verbose_name = 'Asistencia'
        verbose_name_plural = 'Asistencias'

    def toJSON(self):
        item = model_to_dict(self)
        return item


class PermisoInasistencia(models.Model):
    idPermiso = models.AutoField(primary_key=True, verbose_name="idPermiso")
    empleadoo = models.ForeignKey(User, verbose_name='idEmpleadoo', on_delete=models.PROTECT,
                                  related_name='idEmpleadoo')
    fechaInasistencia = models.DateField(default=datetime.now, verbose_name='Fecha Inisistencia', null=True, blank=True)
    motivo = models.CharField(max_length=256, verbose_name="Motivo", null=False, default="", blank=True)
    comentario = models.CharField(max_length=256, verbose_name="Comentario", null=True, blank=True)
    estatus = models.CharField(max_length=64, verbose_name="Estatus", default="PENDIENTE", null=False)
    fechaCreacion = models.DateField(default=datetime.now, verbose_name='Fecha Creacion', null=True, blank=True)

    def __str__(self):
        return self.empleadoo.last_name

    class Meta:
        db_table = 'PermisoInasistencia'
        verbose_name = 'PermisoInasistencia'
        verbose_name_plural = 'PermisoInasistencias'

    def toJSON(self):
        item = model_to_dict(self)
        item['empleado'] = self.empleadoo.toJSON()
        return item


class Agendarllamada(models.Model):
    idAgenda = models.AutoField(primary_key=True, verbose_name='idAgenda')
    user_al = models.ForeignKey(User, verbose_name='Empleado Agenda', on_delete=models.PROTECT)
    cliente_al = models.ForeignKey(Clientes, verbose_name='Cliente Agenda', on_delete=models.PROTECT)
    fechaAgenda = models.DateTimeField(null=True, default=datetime.now, verbose_name='Fecha agenda')
    fechaLlamada = models.DateTimeField(null=True, verbose_name='Fecha Llamada')
    color = models.CharField(max_length=20, null=True, verbose_name='Color', blank=True)
    estatus = models.CharField(max_length=20, null=True, verbose_name='Estatus', blank=True)
    comentario = models.CharField(max_length=100, null=True, verbose_name='Comentario', blank=True)
    url = models.CharField(max_length=128, verbose_name='Url', null=True, blank=True)
    categoria = models.CharField(max_length=20, null=True, verbose_name='Comentario', blank=True)

    def __str__(self):
        return self.empleado_al

    class Meta:
        db_table = 'Agendarllamada'
        verbose_name = 'Agendarllamada'
        verbose_name_plural = 'Agendarllamada'

    def toJSON(self):
        item = model_to_dict(self)
        item['empleado_al'] = self.empleado_al.toJSON()
        item['cliente_al'] = self.cliente_al.toJSON()
        return item


class Cita(models.Model):
    idCita = models.AutoField(primary_key=True, verbose_name='idCita')
    empleado_c = models.ForeignKey(User, verbose_name='Empleado Cita', on_delete=models.PROTECT)
    razonSocial = models.CharField(max_length=128, null=True, verbose_name='Razon Social', blank=True)
    responsable = models.CharField(max_length=128, null=True, verbose_name='Responsable', blank=True)
    fechaAgenda = models.DateTimeField(null=True, default=datetime.now, verbose_name='Fecha agenda')
    fechaCita = models.DateTimeField(null=True, verbose_name='Fecha Cita')
    color = models.CharField(max_length=20, null=True, verbose_name='Color', blank=True)
    estatus = models.CharField(max_length=20, null=True, verbose_name='Estatus', blank=True)
    url = models.CharField(max_length=50, verbose_name='Url', null=True, blank=True)

    def __str__(self):
        return self.empleado_c

    class Meta:

sicovg/core/principales/principalesviews/views.py
from datetime import datetime, timedelta
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView


class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = 'dashboard.html'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        self.id = request.user.id
        self.usuario = request.user
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Dashboard'
        return context


def page_not_found404(request, exception):
    return render(request, '404.html')

sicovg/core/principales/templates/dashboard.html
{% extends 'layout.html' %}
{% load static %}
{% block head %}

    <link rel="stylesheet" type="text/css" href="{% static 'lib/bootstrap-4.4.1-dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'lib/toastr-2.1.4/toastr/toastr.css' %}">
    <script type="text/javascript" src="{% static 'lib/toastr-2.1.4/toastr/toastr.js' %}"></script>
    {#    Lobrerías de gráfica #}
    <script src="{% static 'lib/highcharts-8.1.2/highcharts.js' %}"></script>
    <script src="{% static 'lib/highcharts-8.1.2/modules/exporting.js' %}"></script>
    <script src="{% static 'lib/highcharts-8.1.2/modules/export-data.js' %}"></script>
    <script src="{% static 'lib/highcharts-8.1.2/modules/accessibility.js' %}"></script>
    <script src="{% static 'lib/toastr-2.1.4/JS/notificacionesGenerales.js' %}"></script>
{% endblock %}

{% block encabezadoBienvenida %}
    <div class="row">
        <div class="col-sm-8">
            <h3 class="m-0 text-dark"> Bienvenido <small>{{ request.user.get_full_name }}</small>
            </h3>
        </div>
         <div class="col-sm-4">
            <ol class="breadcrumb float-sm-right">
                {#<li class="breadcrumb-item"><a href="{% url 'principales:dashboard' %}">Home</a></li>#}
                <li class="breadcrumb-item"><a href="{{ list_url }}">{{ entity }}</a></li>
            </ol>
        </div>
    </div>
    <input type="hidden" value="{{ NotiPermisos }}" name="NotiPermisos" id="NotiPermisos">
    <hr>
    {% if request.user.tipoEmpleado.upper == 'VENTAS' %}
        <script>
            window.location.href = "/erp/empresa/ver/";
        </script>
    {% endif %}
    <!-- Small boxes (Stat box) -->
    {% if request.user.tipoEmpleado != 'MESA DE CONTROL' and  request.user.tipoEmpleado != 'RH' %}
        <div class="row">
            <div class="col-12 col-sm-6 col-md-3">
                <div class="info-box">
                    <span class="info-box-icon col-bluest elevation-1"><i class="fas fa-clipboard-check"></i></span>
                    <div class="info-box-content">
                        <span class="info-box-text">Ingreso</span>
                        <span class="info-box-number">{{ estatus.ingreso }}</span>
                    </div>
                </div>
                <!-- /.info-box -->
            </div>
            <!-- /.col -->
            <div class="col-12 col-sm-6 col-md-3">
                <div class="info-box mb-3">
                    <span class="info-box-icon col-greent elevation-1"><i class="fas fa-file-invoice-dollar"></i></span>

                    <div class="info-box-content">
                        <span class="info-box-text">Facturada</span>
                        <span class="info-box-number">{{ estatus.facturada }}</span>
                    </div>
                    <!-- /.info-box-content -->
                </div>
                <!-- /.info-box -->
            </div>
            <!-- /.col -->

            <!-- fix for small devices only -->
            <div class="clearfix hidden-md-up"></div>

            <div class="col-12 col-sm-6 col-md-3">
                <div class="info-box mb-3">
                    <span class="info-box-icon col-yellowt elevation-1"><i class="fas fa-sync-alt"></i></span>

                    <div class="info-box-content">
                        <span class="info-box-text">Rechazo de Almacen</span>
                        <span class="info-box-number">{{ estatus.almacen }}</span>
                    </div>
                    <!-- /.info-box-content -->
                </div>
                <!-- /.info-box -->
            </div>
            <!-- /.col -->
            <div class="col-12 col-sm-6 col-md-3">
                <div class="info-box mb-3">
                    <span class="info-box-icon col-redt elevation-1"><i class="fas fa-exclamation-triangle"></i></span>

                    <div class="info-box-content">
                        <span class="info-box-text">Rechazo de Mesa</span>
                        <span class="info-box-number">{{ estatus.mesa }}</span>
                    </div>
                    <!-- /.info-box-content -->
                </div>
                <!-- /.info-box -->
            </div>
            <!-- /.col -->
            <div class="col-12 col-sm-6 col-md-3">
                <div class="info-box mb-3">
                    <span class="info-box-icon btn-dark elevation-1"><i class="fas fa-file-download"></i></span>

                    <div class="info-box-content">
                        <span class="info-box-text">Contrato enviado</span>
                        <span class="info-box-number">{{ estatus.contratoEnviado }}</span>
                    </div>
                    <!-- /.info-box-content -->
                </div>
                <!-- /.info-box -->
            </div>
        </div>
    {% endif %}
    {% if request.user.tipoEmpleado.upper == "ADMINISTRADOR" or "ADMINISTRADOR_TOLUCA" or request.user.tipoEmpleado.upper == "MESA DE CONTROL" %}
        <figure class="highcharts-figure">
            <div id="container"></div>
            <script type="application/javascript">
                Highcharts.chart('container', {
                    chart: {
                        type: 'column'
                    },
                    title: {
                        text: 'Gráfica General de Estatus'
                    },
                    xAxis: {
                        categories: [
                            'Estatus'
                        ],
                        crosshair: true
                    },
                    yAxis: {
                        min: 0,
                        title: {
                            text: 'Total de Cuentas'
                        }
                    },
                    tooltip: {
                        headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
                        pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                            '<td style="padding:0"><b>{point.y:.1f} Cuentas</b></td></tr>',
                        footerFormat: '</table>',
                        shared: true,
                        useHTML: true
                    },
                    plotOptions: {
                        column: {
                            pointPadding: 0.2,
                            borderWidth: 0
                        }
                    },
                    series: [{
                        name: 'Rechazo de Mesa de Control',
                        data: [{{estatusG.rechazoMesaG}}]

                    }, {
                        name: 'Abiertas',
                        data: [{{estatusG.abiertaG}}]

                    }, {
                        name: 'Ingreso',
                        data: [{{estatusG.ingresoG}}]

                    }, {
                        name: 'Validación de Producto',
                        data: [{{estatusG.validacionDeProductoG}}]

                    }, {
                        name: 'Validación de Crédito',
                        data: [{{estatusG.validacionCreditoG}}]

                    }, {
                        name: 'Rechazo de Crédito',
                        data: [{{estatusG.rechazoDeCreditoG}}]

                    }, {
                        name: 'Almacén',
                        data: [{{estatusG.almacenG}}]

                    }, {
                        name: 'Rechazo de Almacén',
                        data: [{{estatusG.almacenG}}]

                    }, {
                        name: 'Facturada',
                        data: [{{estatusG.facturadaG}}]

                    }]
                });
            </script>
        </figure>
    {% endif %}
{% endblock %}

sicovg/core/principales/templates/delete.html
{% extends 'layout.html' %}
{% load widget_tweaks %}
{% block content %}
    <form method="post" action=".">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">
                    <i class="fas fa-trash"></i>
                    {{ title }}
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                <input type="hidden" name="action" value="{{ action }}">
                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h5><i class="icon fas fa-ban"></i> Ha ocurrido un error al querer guardar el registro</h5>
                        <ul>
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                <div class="alert alert-danger alert-dismissible">
                    <h5><i class="icon fas fa-ban"></i> Notificación!</h5>
                    ¿Estas seguro de eliminar el registro N°{{ object.id }}?
                    {% block htmlExtra %}
                    {% endblock %}
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary btn-flat">
                    <i class="fas fa-save"></i> Si, aceptar
                </button>
                <a href="{{ list_url }}" class="btn btn-danger btn-flat">
                    <i class="fas fa-times"></i> Cancelar
                </a>
            </div>
        </div>
    </form>
    <script>
        $('form').on('submit', function (e) {
            e.preventDefault();
            var parameters = new FormData(this);
            submit_with_ajax(window.location.pathname, 'Notificación', '¿Estas seguro de eliminar el siguiente registro?', parameters, function () {
                Swal.fire({
                    title: 'Alerta',
                    text: 'Registro eliminado correctamente',
                    icon: 'success',
                    timer: 2000,
                    onClose: () => {
                        location.href = '{{ list_url }}';
                    }
                });
                //location.href = '{{ list_url }}';
            });
        });
    </script>
{% endblock %}

sicovg/core/principales/templates/footer.html
<!-- Main Footer -->
<footer class="main-footer text-center">
    <strong>Copyright &copy; 2023 KNT</strong><br>
    Todos los derechos reservados.
</footer>

sicovg/core/principales/templates/form.html
{% extends 'layout.html' %}
{% load widget_tweaks %}
{% block head %}
    {% block head_form %}

    {% endblock %}
{% endblock %}
{% block content %}
    {% block content_encabezado %}

    {% endblock %}
    <form method="post" action="." enctype="multipart/form-data" id="frmActivo" name="frmActivo">
        <div class="card">
            <div class="card-header col-greent">
                <h3 class="card-title">
                    {% if action == 'add' %}
                        <i class="fas fa-plus"></i>
                    {% else %}
                        <i class="fas fa-edit"></i>
                    {% endif %}

                    {{ title }}
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                <input type="hidden" name="action" value="{{ action }}">
                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h5><i class="icon fas fa-ban"></i> Ha ocurrido un error al querer guardar el registro</h5>
                        <ul>
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                {% block formulario %}
                    {% for field in form.visible_fields %}
                        <div class="form-group">
                            <label for="email">{{ field.label }}:</label>
                            {{ field|add_class:'form-control'|attr:'autocomplete:off' }}
                        </div>
                    {% endfor %}
                {% endblock %}
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-yellowt btn-flat">
                    <i class="fas fa-save"></i> Guardar registro
                </button>
                <a href="{{ list_url }}" class="btn btn-redt btn-flat">
                    <i class="fas fa-times"></i> Cancelar
                </a>
            </div>
        </div>
    </form>

    {% block content_pie %}
    {% endblock %}
    <script>
        {% if form.errors %}
            var errors = '';
            {% for field in form %}
                {% for error in field.errors %}
                    errors += '{{ error }}\n';
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                errors += '{{ error }}\n';
            {% endfor %}
            Swal.fire({
                title: 'Error!',
                text: errors,
                icon: 'error'
            });
        {% endif %}
        {% block AJAX %}
            $('form').on('submit', function (e) {
                e.preventDefault();
                var parameters = new FormData(this);
                submit_with_ajax(window.location.pathname, 'Notificación', '¿Estas seguro de realizar la siguiente acción?', parameters, function () {
                    Swal.fire({
                        title: 'Alerta',
                        text: '¡Se ha guardado correctamente!',
                        icon: 'success',
                        timer: 2000,
                        onClose: () => {
                            location.href = '{{ list_url }}';
                        }
                    });
                });
            });
        {% endblock %}
    </script>
{% endblock %}

sicovg/core/principales/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/sicov-icon.png' %}" type="image/png"/>
    <title>{{ title }}</title>
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.0.4/plugins/font-awesome-5.11.1/css/all.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.0.4/css/adminlte.css' %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <!-- jQuery -->
    <script src="{% static 'lib/adminlte-3.0.4/plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'lib/adminlte-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'lib/adminlte-3.0.4/js/adminlte.min.js' %}"></script>
    <!-- Sweetalert2 -->
    <script src="{% static 'lib/sweetalert2-9.10.0/sweetalert2.all.min.js' %}"></script>
    <!-- Jquery Confirm -->
    <link rel="stylesheet" href="{% static 'lib/jquery-confirm-v3.3.4/jquery-confirm.min.css' %}">
    <script src="{% static 'lib/jquery-confirm-v3.3.4/jquery-confirm.min.js' %}"></script>
    <!-- My css -->
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
      <link rel="stylesheet" href="{% static 'css/new_style.css' %}">
    <!-- Functions -->
    <script src="{% static 'js/functions.js' %}"></script>
    <!-- Funcion pantalla de carga -->
    <script src="{% static 'js/pantallaCarga.js' %}"></script>
    <!--Font Awesone Icons 5-->
    <script src="https://kit.fontawesome.com/yourcode.js" crossorigin="anonymous"></script>
    <!-- Estilos de carga-->
    <link rel="stylesheet" href="{% static 'css/estilosCarga.css' %}">
    <script src="https://kit.fontawesome.com/ff4ba701a0.js" crossorigin="anonymous"></script>
    {% block head %}

    {% endblock %}
</head>
<body>
{% block body %}

{% endblock %}
</body>
</html>

sicovg/core/principales/templates/layout.html
{% extends 'vtc/body.html' %}

sicovg/core/principales/templates/list.html
{% extends 'layout.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'lib/datatables-1.10.20/css/dataTables.bootstrap4.min.css' %}"/>
    <link rel="stylesheet"
          href="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/css/responsive.bootstrap4.min.css' %}"/>
    <script src="{% static 'lib/datatables-1.10.20/js/jquery.dataTables.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/responsive.bootstrap4.min.js' %}"></script>

    {% block head_list %}

    {% endblock %}

{% endblock %}

{% block content %}
    <div class="card">
        <div class="card-header col-greent">
            <h3 class="card-title">
                <i class="fas fa-search"></i>
                {{ title }}
            </h3>
        </div>
        <div class="card-body">
           <table class="table table-bordered w-auto" id="data">
    <thead>
        {% block columns %}
        {% endblock %}
    </thead>
    <tbody>
        {% block rows %}
        {% endblock %}
    </tbody>
</table>


        </div>
        <div class="card-footer">
            {% block buttons_list %}
                <a href="{{ create_url }}" class=" btn btn-yellowt ">
                    <i class="fas fa-plus"></i> Nuevo registro
                </a>
                <a href="{{ list_url }}" class="btn btn-yellowt">
                    <i class="fas fa-sync"></i> Actualizar
                </a>
            {% endblock %}
        </div>
    </div>
{% endblock %}

{% block javascript %}
    <script type="application/javascript">
        $(function () {
            $('#data').DataTable({
                responsive: true,
                autoWidth: false
            });

            $('.btnTest').on('click', function () {
                $.ajax({
                    {#url: '{% url 'erp:category_list' %}',#}
                    type: 'POST',
                    data: {id: 1},
                    dataType: 'json'
                }).done(function (data) {
                    console.log(data);
                }).fail(function (jqXH, textStatus, errorThrown) {
                    alert(textStatus + ': ' + errorThrown);
                }).always(function (data) {

                });
            });
        });
    </script>
{% endblock %}