sicovg/core/Agendacalend/urls.py
from core.Agendacalend.views.agendarLlamada.calendario import CalendarioLlamadaView, CalendarioListLlamadaView, \
    CalendarioCreateLlamadaView
from django.urls import path
from core.Agendacalend.views.agendarLlamada import calendario
from core.Agendacalend.views.empresa.views import Ventaview


app_name = 'Agendacalend'

urlpatterns = [
    # Empresa
    path('empresa/detalle/', Ventaview.as_view(), name='empresa_datelle_cuenta'),

    # Agendar llamada
    path('editarevent/<int:id>/', calendario.editarevent, name='editarevent'),
    path('eliminarevent/<int:id>/', calendario.eliminarevent, name='eliminarevent'),
    path('eliminacionid/<int:id>/', calendario.eliminacionid, name='eliminacionid'),
    path('agendarLlamada/', CalendarioLlamadaView.as_view(), name='c_llamada'),
    path('agendarLlamada/list/', CalendarioListLlamadaView.as_view(), name='l_llamada'),
    path('agendarLlamada/create/<str:cuenta>/', CalendarioCreateLlamadaView.as_view(), name='cr_llamada'),
]

sicovg/core/Clientes/urls.py
from django.urls import path

from core.Clientes.views import ClienteView, ClienteCreateView, ClienteUpdateView, ClienteDeleteView

app_name = 'Clientes'

urlpatterns = [
    path('List/', ClienteView.as_view(), name='Cliente'),
    path('Create/', ClienteCreateView.as_view(), name='Create_cliente'),
    path('Update/<int:pk>/', ClienteUpdateView.as_view(), name='Update_cliente'),
    path('Delete/<int:pk>/', ClienteDeleteView.as_view(), name='Delete_cliente'),
]

sicovg/sicovg/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from sicovg import settings
urlpatterns = [
    path('', include('core.login.urls')),
    path('Inicio/', include('core.principales.urls')),
    path('Clientes/', include('core.Clientes.urls')),
    path('Proovedores/', include('core.Proovedores.urls')),
    path('Inventario/', include('core.Inventario.urls')),
    path('Ventas/', include('core.Ventas.urls')),
    path('rh/', include('core.rh.urls')),
    path('Agendacalend/', include('core.Agendacalend.urls')),
]

sicovg/core/login/models.py
from email.message import EmailMessage
from datetime import datetime
import random
from django.core.mail import EmailMessage
import smtplib
import sicovg.settings as settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.forms import model_to_dict
# from core.erp.models import CodigosPostales
from core.login.choices import user_choices, gender_choices


class CodigosPostales(models.Model):
    idCodigoPostal = models.IntegerField(primary_key=True, verbose_name='idCodigoPostal')
    Codigo = models.IntegerField(verbose_name='Codigo', null=True, blank=True)
    Municipio = models.CharField(max_length=128, verbose_name='Municipio', null=True, blank=True)
    Estado = models.CharField(max_length=128, verbose_name='Estado', null=True, blank=True)
    Colonia = models.CharField(max_length=128, verbose_name='Colonia', null=True, blank=True)

    def __str__(self):
        return '{} / {} / {}'.format(self.Municipio, self.Estado, self.Colonia)

    def get_full_name(self):
        return '{} / {} / {}'.format(self.Municipio, self.Estado, self.Colonia)

    class Meta:
        db_table = 'CodigosPostales'
        verbose_name = 'CodigoPostal'
        verbose_name_plural = 'CodigosPotales'

    def toJSON(self):
        item = model_to_dict(self, exclude=['id'])
        item['id'] = self.idCodigoPostal
        return item





class User(AbstractUser):
    last_name_m = models.CharField(max_length=64, verbose_name='Apellido Materno', null=True)
    calle = models.CharField(max_length=128, verbose_name='Calle', null=True)
    noExt = models.CharField(max_length=15, verbose_name='No exterior', default='SN')
    noInt = models.CharField(max_length=15, verbose_name='No interior', default='SN')
    codigoPostal = models.CharField(verbose_name='Codigo Postal', max_length=5, null=True, blank=True)
    municipio = models.CharField(verbose_name='Municipio', max_length=128, null=True, blank=True)
    estado = models.CharField(verbose_name='Estado', max_length=64, null=True, blank=True)
    colonia = models.CharField(verbose_name='Colonia', max_length=128, null=True, blank=True)
    tipoEmpleado = models.CharField(max_length=25, choices=user_choices, default='Ejecutivo',
                                    verbose_name='Tipo de Empleado')
    telefonoPersonal = models.CharField(max_length=10, verbose_name='Telefono personal', null=True)
    fechaNacimiento = models.DateField(default=datetime.now, verbose_name='Fecha de nacimiento', null=True, blank=True)
    parentesco = models.CharField(max_length=64, verbose_name='Parentesco', null=True, blank=True)
    token = models.UUIDField(primary_key=False, editable=False, null=True, blank=True)
    generated_username = models.CharField(max_length=100, blank=True)
    generated_password = models.CharField(max_length=100, blank=True)

    # Convertir el modelo a un diccionario de datos para una mejor manipulación
    def toJSON(self):
        item = model_to_dict(self, exclude=['last_login', 'groups', 'user_permissions', 'password'])
        if self.last_login:
            item['last_login'] = self.last_login.strftime('%Y-%m-%d')
        if self.fechaNacimiento:
            item['fechaNacimiento'] = self.fechaNacimiento.strftime('%Y-%m-%d')
        if self.fechaBaja:
            item['fechaBaja'] = self.fechaBaja.strftime('%Y-%m-%d')
        item['date_joined'] = self.date_joined.strftime('%Y-%m-%d')
        item['full_name'] = '{} {} {}'.format(self.first_name, self.last_name, self.last_name_m)
        item['colaborador'] = self.comprobarArchivo(self.colaborador)
        return item

    # sobreescribir el metodo save de django, para poder cifrar la contraseña del usuario y personalizar el usuario
    def contraseña(self):
        longitud = 8
        valores = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ<=>@#%&+"
        p = "".join([random.choice(valores) for i in range(longitud)])
        print(p)
        return p

    def nombreUsuario(self):
        return '{}{}{}{}'.format(self.first_name[0].upper(), self.last_name.upper(), self.last_name_m[0].upper(),
                                 self.edad)

    def save(self, *args, **kwargs):
        if self.pk is None:
            contra = self.contraseña()
            self.username = self.nombreUsuario()
            self.set_password(contra)
            self.generated_username = self.username
            self.generated_password = contra
        super().save()
        try:
            remitente = "sistemas.kon.knt@gmail.com"
            destinatario = "isabeltrujillo.konect@gmail.com"
            mensaje = 'Tu contraseña es: ' + contra + ' y tu usuario es: ' + self.nombreUsuario()
            email = EmailMessage()
            email['From'] = remitente
            email['To'] = destinatario
            email['Subject'] = 'USUARIO SICOV'
            email.set_content(mensaje)
            smtp = smtplib.SMTP_SSL('smtp.gmail.com')
            smtp.login(remitente, 'mltiukpaeqibddqo')
            smtp.sendmail(remitente, destinatario, email.as_string())
            smtp.quit()
        except Exception as e:
            print(str(e))

    def comprobarArchivo(self, archivo):
        if archivo != "":
            return '{}'.format(settings.MEDIA_URL, archivo)
        return '#!'

def upload_path_handler(instance, filename):
    return "expedienteuser/{}/{}".format(instance.idEmpleado, filename)

sicovg/core/principales/models.py
from django.db import models
from django.forms import model_to_dict
from datetime import datetime
from datetime import date
from core.login.models import User


class Clientes(models.Model):
    idCliente = models.AutoField(primary_key=True, verbose_name='idCliente')
    razonSocial = models.CharField(max_length=256, verbose_name='Razon social', null=False, unique=False)
    cuenta = models.CharField(max_length=6, verbose_name='Numero de cuenta', null=False, unique=False)
    email = models.CharField(max_length=128, verbose_name='Email', blank=True, null=True)
    RFC = models.CharField(max_length=18, verbose_name='RFC', unique=False)
    calle = models.CharField(max_length=128, verbose_name='Calle', null=True, blank=True)
    noExt = models.CharField(max_length=15, verbose_name='No exterior', default='SN', blank=True)
    noInt = models.CharField(max_length=15, verbose_name='No Interior', default='SN', blank=True)
    codigoPostal = models.CharField(verbose_name='Codigo Postal', max_length=5, null=True, blank=True)
    municipio = models.CharField(verbose_name='Municipio', max_length=128, null=True, blank=True)
    estado = models.CharField(verbose_name='Estado', max_length=64, null=True, blank=True)
    colonia = models.CharField(verbose_name='Colonia', max_length=128, null=True, blank=True)
    telefono = models.CharField(max_length=10, verbose_name='Telefono', null=True, blank=True)

    class Meta:
        db_table = 'Cliente'
        verbose_name = 'cliente'
        verbose_name_plural = 'Clientes'

    def toJSON(self):
        item = model_to_dict(self)
        return item


class Proovedor(models.Model):
    idProveedor = models.AutoField(primary_key=True, verbose_name='idProveedor')
    razonSocial = models.CharField(max_length=256, null=False, unique=False)
    cuenta = models.CharField(max_length=10, verbose_name='Cuenta', unique=True)
    RFC = models.CharField(max_length=18, verbose_name='RFC', unique=False)
    codigoPostal = models.CharField(verbose_name='Codigo Postal', max_length=5, null=True, blank=True)
    municipio = models.CharField(verbose_name='Municipio', max_length=128, null=True, blank=True)
    estado = models.CharField(verbose_name='Estado', max_length=64, null=True, blank=True)
    colonia = models.CharField(verbose_name='Colonia', max_length=128, null=True, blank=True)
    telefono = models.CharField(max_length=10, verbose_name='Telefono', null=True, blank=True)
    email = models.CharField(max_length=128, verbose_name='Email', blank=True, null=True)
    activo = models.CharField(max_length=5, verbose_name='Activo', null=True, blank=True)
    representanteLegal = models.CharField(max_length=128, verbose_name='Representante legal', null=True, blank=True)

    class Meta:
        db_table = 'Proovedor'
        verbose_name = 'Proovedor'
        verbose_name_plural = 'Proovedores'

    def toJSON(self):
        item = model_to_dict(self)
        return item


class Inventario(models.Model):
    idInventario = models.AutoField(primary_key=True, verbose_name='idInventario')
    NombresProducto = models.CharField(max_length=100, verbose_name='Nombre Producto', null=False)
    Descripcion = models.CharField(max_length=200, verbose_name=' Descripcion', null=False)
    Categoria = models.CharField(max_length=100, verbose_name='Categoria ', null=False)
    NumeroDeSerie = models.CharField(max_length=20, verbose_name=' Numero De Serie', null=False)
    CantidadDeStock = models.IntegerField(verbose_name=' Cantidad En Stock', null=False)
    PrecioUnitario = models.FloatField(max_length=50, verbose_name=' Precio Unitario', null=False)
    PrecioDeCompra = models.FloatField(max_length=50, verbose_name=' Precio De Compra', null=False)
    FechaDeCompra = models.DateField(default=datetime.now, verbose_name='Fecha De Compra', null=False)
    NivelDeReordenamiento = models.IntegerField(verbose_name=' Numero De Ordenamiento ', null=False)

    class Meta:
        db_table = 'Inventario'
        verbose_name = 'Inventario'
        verbose_name_plural = 'Inventarios'

    def toJSON(self):
        item = model_to_dict(self)
        return item


class Venta(models.Model):
    idVenta = models.AutoField(primary_key=True, verbose_name='idVenta')
    clienteId = models.ForeignKey(Clientes, verbose_name='idCliente', on_delete=models.PROTECT)
    colaboradorId = models.ForeignKey(User, verbose_name=id, on_delete=models.PROTECT)
    totalDeVentas = models.FloatField(max_length=50, verbose_name='Total de Venta', null=False)
    fechaDeCompra = models.DateField(default=date.today, verbose_name='Fecha de Compra', null=False)
    estatus = models.CharField(max_length=100, verbose_name='Estatus', null=False)
    comentario = models.CharField(max_length=250, verbose_name='Estatus', null=False)

    class Meta:
        db_table = 'Venta'
        verbose_name = 'Venta'
        verbose_name_plural = 'Ventas'

    def toJSON(self):
        item = model_to_dict(self)
        return item


class DetalleVenta(models.Model):
    idDetalleVenta = models.AutoField(primary_key=True, verbose_name='idDetalleVenta')
    ventaId = models.ForeignKey(Venta, verbose_name='idVenta', on_delete=models.PROTECT)
    inventarioId = models.ForeignKey(Inventario, verbose_name='idInventario', on_delete=models.PROTECT)
    cantidad = models.IntegerField(verbose_name='Cantidad', null=False)
    precioUnitario = models.FloatField(max_length=50, verbose_name='Precio Unitario', null=False)
    precioTotal = models.FloatField(max_length=50, verbose_name='Precio Total', null=False)
    fechaDeCompra = models.DateField(default=date.today, verbose_name='Fecha de Compra', null=False)

    class Meta:
        db_table = 'DetalleVenta'
        verbose_name = 'DetalleVenta'
        verbose_name_plural = 'DetalleVentas'

    def toJSON(self):
        item = model_to_dict(self)
        return item


class Asistencia(models.Model):
    idAsistencia = models.AutoField(primary_key=True, verbose_name="idAsistencia")
    colaborador = models.ForeignKey(User, verbose_name='idColaborador', on_delete=models.PROTECT,
                                    related_name='idColaborador')
    fechaAsistencia = models.DateField(default=datetime.now, verbose_name="Fecha Asistencia", null=True, blank=True)
    estatus = models.CharField(max_length=100, verbose_name='estatus', null=True, blank=True)

    class Meta:
        db_table = 'Asistencia'
        verbose_name = 'Asistencia'
        verbose_name_plural = 'Asistencias'

    def toJSON(self):
        item = model_to_dict(self)
        return item


class PermisoInasistencia(models.Model):
    idPermiso = models.AutoField(primary_key=True, verbose_name="idPermiso")
    empleadoo = models.ForeignKey(User, verbose_name='idEmpleadoo', on_delete=models.PROTECT,
                                  related_name='idEmpleadoo')
    fechaInasistencia = models.DateField(default=datetime.now, verbose_name='Fecha Inisistencia', null=True, blank=True)
    motivo = models.CharField(max_length=256, verbose_name="Motivo", null=False, default="", blank=True)
    comentario = models.CharField(max_length=256, verbose_name="Comentario", null=True, blank=True)
    estatus = models.CharField(max_length=64, verbose_name="Estatus", default="PENDIENTE", null=False)
    fechaCreacion = models.DateField(default=datetime.now, verbose_name='Fecha Creacion', null=True, blank=True)

    def __str__(self):
        return self.empleadoo.last_name

    class Meta:
        db_table = 'PermisoInasistencia'
        verbose_name = 'PermisoInasistencia'
        verbose_name_plural = 'PermisoInasistencias'

    def toJSON(self):
        item = model_to_dict(self)
        item['empleado'] = self.empleadoo.toJSON()
        return item


class Agendarllamada(models.Model):
    idAgenda = models.AutoField(primary_key=True, verbose_name='idAgenda')
    user_al = models.ForeignKey(User, verbose_name='Empleado Agenda', on_delete=models.PROTECT)
    cliente_al = models.ForeignKey(Clientes, verbose_name='Cliente Agenda', on_delete=models.PROTECT)
    fechaAgenda = models.DateTimeField(null=True, default=datetime.now, verbose_name='Fecha agenda')
    fechaLlamada = models.DateTimeField(null=True, verbose_name='Fecha Llamada')
    color = models.CharField(max_length=20, null=True, verbose_name='Color', blank=True)
    estatus = models.CharField(max_length=20, null=True, verbose_name='Estatus', blank=True)
    comentario = models.CharField(max_length=100, null=True, verbose_name='Comentario', blank=True)
    url = models.CharField(max_length=128, verbose_name='Url', null=True, blank=True)
    categoria = models.CharField(max_length=20, null=True, verbose_name='Comentario', blank=True)

    def __str__(self):
        return self.empleado_al

    class Meta:
        db_table = 'Agendarllamada'
        verbose_name = 'Agendarllamada'
        verbose_name_plural = 'Agendarllamada'

    def toJSON(self):
        item = model_to_dict(self)
        item['empleado_al'] = self.empleado_al.toJSON()
        item['cliente_al'] = self.cliente_al.toJSON()
        return item


class Cita(models.Model):
    idCita = models.AutoField(primary_key=True, verbose_name='idCita')
    empleado_c = models.ForeignKey(User, verbose_name='Empleado Cita', on_delete=models.PROTECT)
    razonSocial = models.CharField(max_length=128, null=True, verbose_name='Razon Social', blank=True)
    responsable = models.CharField(max_length=128, null=True, verbose_name='Responsable', blank=True)
    fechaAgenda = models.DateTimeField(null=True, default=datetime.now, verbose_name='Fecha agenda')
    fechaCita = models.DateTimeField(null=True, verbose_name='Fecha Cita')
    color = models.CharField(max_length=20, null=True, verbose_name='Color', blank=True)
    estatus = models.CharField(max_length=20, null=True, verbose_name='Estatus', blank=True)
    url = models.CharField(max_length=50, verbose_name='Url', null=True, blank=True)

    def __str__(self):
        return self.empleado_c

    class Meta:

sicovg/core/Agendacalend/templates/empresa/detalleCuenta.html
{% extends 'form.html' %}
{% load widget_tweaks %}
{% load static %}
{% block head_form %}
    {#    Query#}
    <link href="{% static 'lib/jquery-ui-1.12.1/jquery-ui.min.css' %}" rel="stylesheet"/>
    <script src="{% static 'lib/jquery-ui-1.12.1/jquery-ui.min.js' %}"></script>

    <link href="{% static 'lib/select2-4.0.13/css/select2.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'lib/select2-4.0.13/css/select2-bootstrap4.min.css' %}" rel="stylesheet"/>
    <script src="{% static 'lib/select2-4.0.13/js/select2.min.js' %}"></script>
    <script src="{% static 'lib/select2-4.0.13/js/i18n/es.js' %}"></script>

    <link rel="stylesheet" href="{% static 'lib/datatables-1.10.20/css/dataTables.bootstrap4.min.css' %}"/>
    <link rel="stylesheet"
          href="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/css/responsive.bootstrap4.min.css' %}"/>
    <script src="{% static 'lib/datatables-1.10.20/js/jquery.dataTables.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/responsive.bootstrap4.min.js' %}"></script>

    <script src="{% static 'empresa/js/detalleCuenta.js' %}"></script>
{% endblock %}
{% block pantallaDeCarga %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-2">
        </div>
        <div class="col-md-8">
            <div class="card ">
                <div class="card-header col-greent ">
                    <h3 class="card-title">Buscar {{ name }}</h3>
                </div>
                <form>
                    <div class="card-body">
                        <div class="row">
                            <div class="form-group col-md-6">
                                <label>Buscar por:</label>
                                <select name="tipoCampo" id="tipoCampo" class="form form-control">
                                    <option value="cuenta">Cuenta</option>
                                    <option value="RFC">RFC</option>
                                </select>
                            </div>
                            <div class="form-group col-md-6">
                                <label>Valor:</label>
                                <input type="text" class="form form-controltt" name="valor" id="valor"
                                       placeholder="Ingrese el valor por favor" autofocus="True" required minlength="6"
                                       maxlength="13">
                            </div>
                            <div class="form-group col-md-6">
                                <input type="submit" class="form form-control btn-yellowt" name="btnDetalle"
                                       id="btnDetalle" value="Aceptar">
                            </div>
                            <div class="form-group col-md-6">
                                <a class="form-control  btn-yellowt" target="_blank" name="agenda" id="agenda" href="#!"> Agendar Llamada </a>
                            </div>
                            <div class="form-group col-md-12">
                                <a href="{% url 'Clientes:Create_cliente' %}" target="_blank"
                                   class="form form-control btn-greent text-center">Registrar nuevo Cliente</a>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
<div>
<div class="card">

      <div class="card-header col-greent ">
                    <h3 class="card-title">Datos del {{ name }}</h3>
                </div>
                <div class="row">
                    <input type="hidden" value="" name="tokenid" id="tokenid">
                    <div class="form-group col-md-3">
                        <label>RazonSocial</label>
                        <input type="text" name="razonSocial" maxlength="128" required
                               onkeyup="javascript:this.value = this.value.toUpperCase();" readonly placeholder="Ingrese la razón social"
                               autocomplete="off" class="form-control" id="id_razonSocial">
                    </div>
                    <div class="form-group col-md-3">
                        <label>Numero de Cuenta</label>
                        <input type="text" name="cuenta" maxlength="10" minlength="6" required readonly placeholder="Ingrese la cuenta"
                               autocomplete="off" class="form-control" id="id_cuenta">
                    </div>
                    <div class="form-group col-md-3">
                        <label>RFC</label>
                        <input type="text" name="RFC" maxlength="18" required
                               onkeyup="javascript:this.value = this.value.toUpperCase();" readonly placeholder="Ingrese el RFC"
                               autocomplete="off" class="form-control" id="id_RFC">
                    </div>
                    <div class="form-group col-md-3">
                        <label>Calle</label>
                        <input type="text" name="calle" maxlength="128" required
                               onkeyup="javascript:this.value = this.value.toUpperCase();" readonly placeholder="Ingrese la calle"
                               autocomplete="off" class="form-control" id="id_calle">
                    </div>
                    <div class="form-group col-md-2">
                        <label>No Exterior</label>
                        <input type="text" name="noExt" value="SN" maxlength="15" required readonly placeholder="Ingrese el no. exterior"
                               autocomplete="off" class="form-control" id="id_noExt">
                    </div>
                    <div class="form-group col-md-2">
                        <label>No Interior</label>
                        <input type="text" name="noInt" value="SN" maxlength="15" required readonly placeholder="Ingrese el no. interior"
                               autocomplete="off" class="form-control" id="id_noInt">
                    </div>
                    <div class="form-group col-md-3">
                        <label>Codigo Postal</label>
                        <div class="input-group">
                            <input type="text" name="codigoPostal" maxlength="5" required readonly class="form-control" id="id_codigoPostal">
                            </i></a>
                        </div>
                    </div>
                    <div class="form-group col-md-4">
                        <label>Estado</label>
                        <input type="text" name="estado" maxlength="64" required readonly class="form-control" id="id_estado">
                    </div>
                    <div class="form-group col-md-4">
                        <label>Municipio</label>
                        <input type="text" name="municipio" maxlength="128" required readonly class="form-control"
                               id="id_municipio">
                    </div>
                    <div class="form-group col-md-4">
                        <label>Colonia</label>
                        <input type="text" name="municipio" maxlength="128" required readonly class="form-control"
                               id="id_colonia">
                    </div>
                    <div class="form-group col-md-4">
                        <label>Email</label>
                        <input type="text" name="email" maxlength="128" required readonly placeholder="Ingrese el email" autocomplete="off"
                               class="form-control" id="id_email">
                    </div>
                    <div class="form-group col-md-3">
                        <label>Telefono</label>
                        <input type="text" name="telefono1" maxlength="10" required readonly placeholder="Ingrese el telefono "
                               autocomplete="off" class="form-control" id="id_telefono">
                    </div>
    </div>
</div>
    </div>
    </div>
 
{% endblock %}

{% block AJAX %}
{% endblock %}

sicovg/core/Agendacalend/templates/empresa/verEmpresas.html
{% extends 'layout.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'lib/datatables-1.10.20/css/dataTables.bootstrap4.min.css' %}"/>
    <link rel="stylesheet"
          href="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/css/responsive.bootstrap4.min.css' %}"/>
    <script src="{% static 'lib/datatables-1.10.20/js/jquery.dataTables.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/responsive.bootstrap4.min.js' %}"></script>
{% endblock %}
{% block content %}
    <div class="card card-info">
        <div class="card-header">
            <h3 class="card-title">Horizontal Form</h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            <table class="table table-bordered" id="data">
                <thead>
                <th style="width: 20%">Razón Social</th>
                <th style="width: 40%">Dirección</th>
                <th style="width: 5%">Código Postal</th>
                <th style="width: 20%">Correo</th>
                <th style="width: 5%">Teléfono</th>
                </thead>
                <tbody>
                {% for e in empresas %}
                    <tr>
                        <td>{{ e.razonSocial }}</td>
                        <td>{{ e.domicilioFiscal }}</td>
                        <td>{{ e.codigoPostal }}</td>
                        <td>{{ e.email }}</td>
                        <td>{{ e.telefono1 }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
            <a href="">Actualizar <i class="fas fa-refresh"></i></a>
        </div>
        <!-- /.card-footer -->
    </div>
{% endblock %}
{% block javascript %}
    <script>
        $('#data').DataTable({
            autoWidth: false,
            destroy: true,
            deferRender: true,
            scrollX: true,
        });
    </script>
{% endblock %}